---
title: "P8122 Homwork 2"
author: "Roxy Zhang"
date: "9/29/2022"
output: html_document
---

```{r setup, include=FALSE}
# install ri from local file
#library(devtools)
#install_local("~/Desktop/P8122/causal_inference/hw2/ri_0.9.tar.gz")

library(ri)
library(tidyverse)
```

```{r}
# read and clean data
df = read_csv("~/Desktop/P8122/causal_inference/hw2/light.csv") %>% 
  janitor::clean_names()
```


```{r}
# plot the outcome by treatment group
ggplot(data = df, aes(x = light, y = bm_gain, color = light)) +
  geom_boxplot()
```

```{r}
# only interested in mice exposed to darkness and bright
# subset the data into two groups
df_sub = df %>% 
  filter(light != "DM")
```


```{r}
# set up the data such that everything needed has generic names
# re-code treatment: dark as 0 and bright as 1
df_setup = df_sub %>% 
  select("light", "bm_gain") %>% 
  rename(A = light,
         Y = bm_gain) %>% 
  mutate(A = case_when(A == "LD" ~ 0,
                       A == "LL" ~ 1))
```


```{r}
# calculate the difference in means between the two treatment groups
y0 = data.frame(df_setup %>% 
                filter(A == 0) %>% 
                select(Y))

avg_y0 = mean(y0$Y)
round(avg_y0, 2)

y1 = data.frame(df_setup %>% 
                filter(A == 1) %>% 
                select(Y))

avg_y1 = mean(y1$Y)
round(avg_y1, 2)

t_obs = round(avg_y1 - avg_y0, 2)
t_obs
```

```{r}
# enumerate different possibilities for A in a matrix
A = c(rep(1, 9), rep(0, 8))
Y = df_setup$Y

Abold = genperms(df_setup$A, maxiter = 30000)

Abold[, 1:15]

ncol(Abold)
```


```{r}
# generate the exact randomization distribution for T
# under the sharp null hypothesis of no difference
rdist <- rep(NA, times = ncol(Abold))
for (i in 1:ncol(Abold)) {
  A_tilde <- Abold[, i]
  rdist[i] <- mean(Y[A_tilde == 1]) - mean(Y[A_tilde == 0])
}

rdist[1:50]
```

```{r}
# t statistics
t_stat = mean(Y[A == 1]) - mean(Y[A == 0])
t_stat
```

```{r echo=TRUE}
# p-value
pval <- mean(rdist >= t_obs)
pval

quant <- quantile(rdist, probs = 1 - pval)
```

```{r}
# plot this distribution, and mark the observed test statistic
hist(rdist)
abline(v = quant,col="red") 
```

